language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - PINS="ocb-stubblr.0.1.1.1:https://github.com/fdopen/ocb-stubblr.git uwt-random:https://github.com/fdopen/uwt-random.git uwt-ssl:https://github.com/fdopen/uwt-ssl.git uwt-tls:https://github.com/fdopen/uwt-tls.git uwt-conduit:https://github.com/fdopen/uwt-conduit.git uwt-cohttp:https://github.com/fdopen/uwt-cohttp.git"
  - POST_INSTALL_HOOK="./.travis-own.sh"
  - TESTS=false
  - PACKAGE=uwt.0.3.3
  - OPAM_VERSION=1.2.2
  matrix:
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      env: OCAML_VERSION=4.05
    - os: linux
      env: OCAML_VERSION=4.06
