val e2big : int
val eacces : int
val eaddrinuse : int
val eaddrnotavail : int
val eafnosupport : int
val eagain : int
val eai_addrfamily : int
val eai_again : int
val eai_badflags : int
val eai_badhints : int
val eai_canceled : int
val eai_fail : int
val eai_family : int
val eai_memory : int
val eai_nodata : int
val eai_noname : int
val eai_overflow : int
val eai_protocol : int
val eai_service : int
val eai_socktype : int
val ealready : int
val ebadf : int
val ebusy : int
val ecanceled : int
val echarset : int
val econnaborted : int
val econnrefused : int
val econnreset : int
val edestaddrreq : int
val eexist : int
val efault : int
val efbig : int
val ehostunreach : int
val eintr : int
val einval : int
val eio : int
val eisconn : int
val eisdir : int
val eloop : int
val emfile : int
val emsgsize : int
val enametoolong : int
val enetdown : int
val enetunreach : int
val enfile : int
val enobufs : int
val enodev : int
val enoent : int
val enomem : int
val enonet : int
val enoprotoopt : int
val enospc : int
val enosys : int
val enotconn : int
val enotdir : int
val enotempty : int
val enotsock : int
val enotsup : int
val eperm : int
val epipe : int
val eproto : int
val eprotonosupport : int
val eprototype : int
val erange : int
val erofs : int
val eshutdown : int
val espipe : int
val esrch : int
val etimedout : int
val etxtbsy : int
val exdev : int
val unknown : int
val eof : int
val enxio : int
val emlink : int
val uwt_unknown : int
val uwt_efatal : int
val uwt_ebadf : int
val uwt_einval : int
val uwt_enotactive : int
val uwt_ebusy : int
